CREATE TABLE public.users (
    id int8 GENERATED BY DEFAULT AS IDENTITY(
        INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE
    ) NOT NULL,
    username varchar(255) NOT NULL,
    "password" varchar(255) NOT NULL,
    fullname varchar(255) NOT NULL,
    created_at timestamp(6) NOT NULL,
    CONSTRAINT uk_users_username UNIQUE (username),
    CONSTRAINT users_pkey PRIMARY KEY (id)
);