CREATE TABLE public.group_participants (
	id int8 GENERATED BY DEFAULT AS IDENTITY(INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	group_id int8 NOT NULL,
	user_id int8 NOT NULL,
	joined_at timestamp(6) NOT NULL,
	CONSTRAINT group_participants_pkey PRIMARY KEY (id),
	CONSTRAINT uk_group_participants_group_user UNIQUE (group_id, user_id)
);

ALTER TABLE public.group_participants ADD CONSTRAINT fk_group_participants_group_id_groups FOREIGN KEY (group_id) REFERENCES public."groups"(id);
ALTER TABLE public.group_participants ADD CONSTRAINT fk_group_participants_user_id_users FOREIGN KEY (user_id) REFERENCES public.users(id);