CREATE TABLE public.messages (
	id int8 GENERATED BY DEFAULT AS IDENTITY(INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	user_id int8 NOT NULL,
	group_id int8 NULL,
	"content" varchar(1000) NOT NULL,
	"timestamp" timestamp(6) NOT NULL,
	CONSTRAINT messages_pkey PRIMARY KEY (id)
);

ALTER TABLE public.messages ADD CONSTRAINT fk_messages_group_id_groups FOREIGN KEY (group_id) REFERENCES public."groups"(id);
ALTER TABLE public.messages ADD CONSTRAINT fk_messages_user_id_users FOREIGN KEY (user_id) REFERENCES public.users(id);