ALTER TABLE public.messages
    ALTER COLUMN content DROP NOT NULL;

ALTER TABLE public.messages
    ADD COLUMN message_type varchar(32) NOT NULL DEFAULT 'TEXT';

CREATE TABLE public.message_media (
    id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message_id int8 NOT NULL,
    attachment_order int4 NOT NULL DEFAULT 0,
    storage_provider varchar(32) NOT NULL,
    bucket varchar(255) NOT NULL,
    object_key varchar(512) NOT NULL,
    original_filename varchar(255) NOT NULL,
    declared_mime_type varchar(255) NOT NULL,
    detected_mime_type varchar(255) NULL,
    size_bytes int8 NOT NULL,
    checksum_sha256 varchar(128) NULL,
    status varchar(64) NOT NULL,
    scan_status varchar(64) NOT NULL,
    width int4 NULL,
    height int4 NULL,
    duration_ms int8 NULL,
    thumbnail_object_key varchar(512) NULL,
    preview_object_key varchar(512) NULL,
    transcoded_object_key varchar(512) NULL,
    created_at timestamp(6) NOT NULL,
    updated_at timestamp(6) NOT NULL,
    CONSTRAINT fk_message_media_message_id_messages FOREIGN KEY (message_id) REFERENCES public.messages(id)
);

CREATE INDEX idx_message_media_message_id_attachment_order
    ON public.message_media (message_id, attachment_order);

CREATE TABLE public.media_uploads (
    id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    upload_id varchar(255) NOT NULL,
    user_id int8 NOT NULL,
    chat_scope varchar(32) NOT NULL,
    group_id int8 NULL,
    upload_session_id varchar(255) NOT NULL,
    requested_message_type varchar(32) NOT NULL,
    requested_filename varchar(255) NOT NULL,
    requested_size_bytes int8 NOT NULL,
    requested_mime_type varchar(255) NOT NULL,
    storage_provider varchar(32) NOT NULL,
    bucket varchar(255) NOT NULL,
    object_key varchar(512) NOT NULL,
    multipart_upload_id varchar(255) NULL,
    status varchar(64) NOT NULL,
    expires_at timestamp(6) NOT NULL,
    created_at timestamp(6) NOT NULL,
    updated_at timestamp(6) NOT NULL,
    CONSTRAINT uk_media_uploads_upload_id UNIQUE (upload_id),
    CONSTRAINT fk_media_uploads_user_id_users FOREIGN KEY (user_id) REFERENCES public.users(id),
    CONSTRAINT fk_media_uploads_group_id_groups FOREIGN KEY (group_id) REFERENCES public.groups(id)
);

CREATE INDEX idx_media_uploads_upload_session_id
    ON public.media_uploads (upload_session_id);
