-- Add participant role column; existing rows default to MEMBER.
ALTER TABLE public.group_participants
    ADD COLUMN role varchar(32) NOT NULL DEFAULT 'MEMBER';

-- Backfill group creators as LEADER when they have no group_participants row yet.
INSERT INTO public.group_participants (group_id, user_id, joined_at, last_read_message_id, role)
SELECT g.id, g.created_by, g.created_at, NULL, 'LEADER'
FROM public."groups" g
WHERE NOT EXISTS (
    SELECT 1
    FROM public.group_participants gp
    WHERE gp.group_id = g.id
      AND gp.user_id = g.created_by
);

-- Promote existing creator rows from MEMBER (default) to LEADER.
UPDATE public.group_participants gp
SET role = 'LEADER'
FROM public."groups" g
WHERE gp.group_id = g.id
  AND gp.user_id = g.created_by;

-- Enforce at most one LEADER per group.
-- This is a partial unique index, aka filtered unique index. The index only includes rows where role = 'LEADER'. Among those rows, group_id must be unique
CREATE UNIQUE INDEX ux_group_participants_one_leader
    ON public.group_participants (group_id)
    WHERE role = 'LEADER';

-- Add optional description and archive metadata to groups.
ALTER TABLE public."groups"
    ADD COLUMN description varchar(1000) NULL,
    ADD COLUMN archived_at timestamp(6) NULL,
    ADD COLUMN archived_by int8 NULL,
    ADD COLUMN archive_reason varchar(64) NULL;

-- Link archived_by to the user who archived the group.
ALTER TABLE public."groups"
    ADD CONSTRAINT fk_groups_archived_by_users FOREIGN KEY (archived_by) REFERENCES public.users(id);

-- Speed up queries that filter or sort by archive status.
CREATE INDEX idx_groups_archived_at
    ON public."groups" (archived_at);

-- Store users banned from a group (one ban record per user per group).
CREATE TABLE public.group_bans (
    id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id int8 NOT NULL,
    user_id int8 NOT NULL,
    banned_by int8 NOT NULL,
    reason varchar(500) NULL,
    banned_at timestamp(6) NOT NULL,
    CONSTRAINT uk_group_bans_group_user UNIQUE (group_id, user_id),
    CONSTRAINT fk_group_bans_group_id_groups FOREIGN KEY (group_id) REFERENCES public."groups"(id),
    CONSTRAINT fk_group_bans_user_id_users FOREIGN KEY (user_id) REFERENCES public.users(id),
    CONSTRAINT fk_group_bans_banned_by_users FOREIGN KEY (banned_by) REFERENCES public.users(id)
);

-- Look up all groups a user is banned from.
CREATE INDEX idx_group_bans_user_id
    ON public.group_bans (user_id);

-- Store invite/join links with hashed tokens and optional expiry/revocation.
CREATE TABLE public.group_join_links (
    id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id int8 NOT NULL,
    token_hash varchar(128) NOT NULL,
    created_by int8 NOT NULL,
    created_at timestamp(6) NOT NULL,
    expires_at timestamp(6) NULL,
    revoked_at timestamp(6) NULL,
    revoked_by int8 NULL,
    CONSTRAINT uk_group_join_links_token_hash UNIQUE (token_hash),
    CONSTRAINT fk_group_join_links_group_id_groups FOREIGN KEY (group_id) REFERENCES public."groups"(id),
    CONSTRAINT fk_group_join_links_created_by_users FOREIGN KEY (created_by) REFERENCES public.users(id),
    CONSTRAINT fk_group_join_links_revoked_by_users FOREIGN KEY (revoked_by) REFERENCES public.users(id)
);

-- Find active (non-revoked, non-expired) join links for a group.
CREATE INDEX idx_group_join_links_group_active
    ON public.group_join_links (group_id, revoked_at, expires_at);

-- Add soft-edit and soft-delete audit columns to messages.
ALTER TABLE public.messages
    ADD COLUMN updated_by int8 NULL,
    ADD COLUMN updated_at timestamp(6) NULL,
    ADD COLUMN deleted_by int8 NULL,
    ADD COLUMN deleted_at timestamp(6) NULL;

-- Link message edit/delete metadata to the acting user.
ALTER TABLE public.messages
    ADD CONSTRAINT fk_messages_updated_by_users FOREIGN KEY (updated_by) REFERENCES public.users(id),
    ADD CONSTRAINT fk_messages_deleted_by_users FOREIGN KEY (deleted_by) REFERENCES public.users(id);

-- Speed up queries that exclude or filter soft-deleted messages.
CREATE INDEX idx_messages_deleted_at
    ON public.messages (deleted_at);

-- Persist prior message content on each edit for audit/history.
CREATE TABLE public.message_edit_history (
    id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message_id int8 NOT NULL,
    old_content varchar(1000) NULL,
    updated_by int8 NOT NULL,
    updated_at timestamp(6) NOT NULL,
    CONSTRAINT fk_message_edit_history_message_id_messages FOREIGN KEY (message_id) REFERENCES public.messages(id),
    CONSTRAINT fk_message_edit_history_updated_by_users FOREIGN KEY (updated_by) REFERENCES public.users(id)
);

-- Load edit history for a message in chronological order.
CREATE INDEX idx_message_edit_history_message_updated_at
    ON public.message_edit_history (message_id, updated_at);
