/**
 * Structured system-event types — mirrors chat-app-backend `SystemEventType`.
 */
export const SYSTEM_EVENT_TYPES = {
  USER_JOINED: "USER_JOINED",
  USER_LEFT: "USER_LEFT",
  USER_KICKED: "USER_KICKED",
  USER_BANNED: "USER_BANNED",
  USER_UNBANNED: "USER_UNBANNED",
  USER_PROMOTED: "USER_PROMOTED",
  USER_DEMOTED: "USER_DEMOTED",
  LEADERSHIP_TRANSFERRED: "LEADERSHIP_TRANSFERRED",
  GROUP_NAME_UPDATED: "GROUP_NAME_UPDATED",
  GROUP_DESCRIPTION_UPDATED: "GROUP_DESCRIPTION_UPDATED",
  GROUP_ARCHIVED: "GROUP_ARCHIVED",
} as const;

export type SystemEventType = (typeof SYSTEM_EVENT_TYPES)[keyof typeof SYSTEM_EVENT_TYPES];
