CREATE TABLE public."groups" (
    id int8 GENERATED BY DEFAULT AS IDENTITY(
        INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE
    ) NOT NULL,
    "name" varchar(255) NOT NULL,
    created_by int8 NOT NULL,
    created_at timestamp(6) NOT NULL,
    CONSTRAINT groups_pkey PRIMARY KEY (id)
);

ALTER TABLE
    public."groups"
ADD
    CONSTRAINT fk_groups_created_by_users FOREIGN KEY (created_by) REFERENCES public.users(id);